### ISSUE TITLE
About model and weights definition

### ISSUE THREAD

**Issue by oeway** [bioimage-io/configuration#21]
After implementing some of my models with the current configuration, I find it a bit less ideal to define a the model and the weights. For example, [this](https://github.com/bioimage-io/tfjs-bioimage-io/blob/master/models/HPAShuffleNetV2/HPAShuffleNetV2.yaml) one in tensorflow.js.

Currently, we use source and kwargs to define the network architecture, which make sense when you have a network created from source code. However, most other model types including tensorflow SavedModel, tfjs PB files, Keras hdf5, ONNX are mostly serialized, source and kwargs does not quite fit any more.

The weights is currently a sub node under prediction, which is the case for most cases. However, weights can also be used by training.

In many cases, the weights and network architecture are come together in one file. In Keras for example, the hdf5 typically contain the model with weights, but it can also saved separately, say, model in a json/yaml file, and weight in a hdf5 file. Besides that, let's say we would like to be compatible with existing model zoo (Pytorch hub and tensorflow hub), we can just provide the source which will also load pertained weights.

As an example, we can define these in the source, and the model will come with pretrained weights, thus we won't need an additional weights field under prediction:
```python
# https://pytorch.org/hub/pytorch_vision_deeplabv3_resnet101/
import torch
def get_deeplabv3_model():
    model = torch.hub.load('pytorch/vision:v0.5.0', 'deeplabv3_resnet101', pretrained=True)
    return model
```

Another example, for my tensorflow.js model with network and weights, I have to define like this
```yaml
source: https://raw.githubusercontent.com/oeway/Anet-Model-Zoo/master/4_hpa_shufflenet_v2/model.json
optional_kwargs: {}
```

And I need to repeat the same url in the `prediction`:
```yaml
prediction:
    preprocess: null
    weights:
        source: https://raw.githubusercontent.com/oeway/Anet-Model-Zoo/master/4_hpa_shufflenet_v2/model.json
    postprocess: []
    dependencies: tfjs
```

I think would be nice to revise the configuration to reflect these cases.

Here is my proposal:
1. add a field called `model`, and add the `source`, `kwargs` and `weights` as subfield (move `weights` from `prediction` to `model`).
2. if the weights are already included in the model, then there is no need to specify the weights
3. to be compatible with existing model zoo/hub, the source cannot only be a class, but also a function which returns a model.

```yaml
# a pytorch model constructed from source, with additional weights file
model:
  source: ./unet2d.py:UNet2d
  kwargs: {input_channels: 1, output_channels: 1}
  weights: https://zenodo.org/record/3446812/files/unet2d_weights.torch

# a tensorflow.js model with network and weights together
model:
 source: https://raw.githubusercontent.com/oeway/Anet-Model-Zoo/master/4_hpa_shufflenet_v2/model.json

# a pretrained model from pytorch hub
model:
  source: ./unet2d.py:get_deeplabv3_model

# a keras model with network and weights saved separately
model:
  source: https://zenodo.org/record/2340240/files/unet2d.json
  weights: https://zenodo.org/record/2340240/files/unet2d.h5
```

Comments, ideas? Please let me know what do you think?

**Comment by FynnBe** [comment]
> 3\. to be compatible with existing model zoo/hub, the source cannot only be a class, but also a function which returns a model.

This is the case already (for any `source` field). `source` needs to point to a callable (in the current python and pytorch implementations). 


> 1\. add a field called `model`, and add the `source`, `kwargs` and `weights` as subfield (move `weights` from `prediction` to `model`).
> 2\. if the weights are already included in the model, then there is no need to specify the weights

👍 especially because, as you mentioned, weights are also relevant to training

**Comment by esgomezm** [comment]
> 1. add a field called `model`, and add the `source`, `kwargs` and `weights` as subfield (move `weights` from `prediction` to `model`).
>
Good!

> 2. if the weights are already included in the model, then there is no need to specify the weights
> 3. to be compatible with existing model zoo/hub, the source cannot only be a class, but also a function which returns a model.
> 
I would add one more case: TensorFlow saved model protobuffer. In this case the model is given by a file called saved_model.pb + a folder called variables containing the variables for the model. How would you define the model in this case? I'm not sure whether the following way is convenient:
> ```yaml
> # a TensorFlow protobuffer model:
> model:
>   source: ./saved_model.pb
>   weights: ./variables/
> ```

**Comment by FynnBe** [comment]
for weights, I'd suggest we keep the source and hash keys, because it might be a url:
```yaml
model: 
  source: ./saved_model.pb
  weights:
    source: www.zenodo.org/record/... some_weights
    hash: {md5: asdfasdfasdf}
```

**Comment by oeway** [comment]
@esgomezm I think since we are hosting the yaml on github to get version controlled, the weights won't be saved in the same folder together with code, so perhaps it's better to think that the weights will come from a remote location, i.e. as an URL as mentioned by @FynnBe .

Since it's hosted elsewhere, it's important to have integrity check by hashing the model and weights file (zip it if you have many files).

I would propose simplify a bit based on @FynnBe 's version in terms of the depth, but add also hashing for the pb file:
```yaml
model: 
  source: 
      url: https://zenodo.org/record.../saved_model.pb
      md5: 0c1bd9d3e602cd2476e33802f614a3b9
  weights:
      url: https://zenodo.org/record/... some_weights.zip
      md5: 6d2b82b991fa1afd90533e2e9c009b0f
```

Like this, if you updated the model file or weights file, you will have to update the hash code, which is great for versioning and reproduciblity.

**Comment by FynnBe** [comment]
we diverged quite a bit from what we have currently... (which isn't necessarily bad, we should just be aware of it) 
if we introduce the following changes
 - move `weights` up to model.yaml root (out of `prediction`)
- remvoe `hash` key and add explicity hash keys. for now only `md5`.

we would end up with a model.yaml like this:
```yaml
...
source: https://zenodo.org/record.../saved_model.pb
md5: 0c1bd9d3e602cd2476e33802f614a3b9
weights:
    source: https://zenodo.org/record/... some_weights.zip
    md5: 6d2b82b991fa1afd90533e2e9c009b0f
```
regarding
- `url`  key: we previously came to the conclusion that having a generic `source` key is the most convenient and allows to use any URI (not just URL), as well as relative local files or an importable object (therefore the key is not called `uri`)
- explicity `model` key: I don't think the model.yaml needs a `model` key. there should only be one `source` and optionally it's associated hash. I don't see a need to nest it further (not a strong reject of the idea though, we do have a lot of keys in root already...)

**Comment by oeway** [comment]
I think it's good to discuss more thoroughly before the implementation. 

1. I thought a bit more and I think it's even better to take out the weight as a root node. 
2. For the hashing, I have no strong opinion to wrap it as `hash: {md5: xxxxxx}` or just `md5: xxxxxx`, my point previously is more about adding hash also for the model pb file. Perhaps it's good to stick with your original proposal. However, I just did a quick search, it seems md5 (or sha1) is not recommended any more due to potential collision. It seems sha256 is a good choice for now, I think we should go for it. Maybe as the only option, to simplify the implementation for different consumer.
3. I would prefer an explicit `model` key, that will make it clear that the `source` and `hash` is for the model definition file, not for model in general.
4. I think you are right for keep the `source` instead of using `url` to cover other cases. 

I would like also to point out that we need to keep in mind that the downside of being too flexible is harder to implement and if there are too many possibilities we will end up with selective implementation for different consumers and the interoperability will be compromised. For now, while think the flexibility, we should limit the options to a minimal necessary level, to ease the implementation and improve consistency.

 For that reason, how about only support `https://` and `file://` for source. For hashing, only 1 hashing algorithm (e.g. sha256, to be decided), and it's mandatory to check the integrity? We can look other fields also to see if we can cut down the cases for now.

**Comment by FynnBe** [comment]
agreed to all! 👍 
I would go even further in restricting `source` for the moment and add only when the need arises... 
for now https://zenodo.org and https://github.com, https://raw.github.com, and https://doi.org.
To use a 'file://' uri is problematic, as we need relative paths that cannot be specified as uri, therefore I would add relative paths and the `::` syntax to specify the object name within the source (if applicable): `uri::object` or `./relative/path/to/local/file::object

```yaml
model: 
  source: ./saved_model.pb
  sh256: asdfasdfasdfasdfasdfasdf
  weights:  # optional for certain types of model sources
    source: https://zenodo.org/record/... some_weights
    sh256: asdfasdfasdfasdfasdfasdf
```

**Comment by oeway** [comment]
Good!

We can certainly give recommendation for the remote source, however, put restrictions on the source would require extra work on the implementation side right? You will store a source list and need to be updated later. I would rather not do it for the moment, but maybe you have a better reason for that.

Would it make sense to take out the `weights` and put under root as you proposed previously? I like that fact the nodes not so deep. And the weights would deserve a root node since we may extend it to a list of weights, or some dynamic weights list loading later.

Right, I just checked also for the `file://` and you are right, it's impossible to use it for relative path.

For uri to object/function, it seems very conventional to use `::`, so I think it's good to stick with that. However, I would prefer if we could limit the type to only a function (not class) if we consider the applicability across different programming language. The reason is that for Java/Javascript/C++ etc., instantiate a class is different from calling a function. If it's a class, you need to add `new` keyword before the class name. It would be more consistent and easier to implement if the uri only point to a function, and the function will return the object. For example, `./relative/path/to/local/file::get_unet2d` instead of `./relative/path/to/local/file::UNet2D`. How does that sounds to you?

Please also change `sh256` to `sha256`.

**Comment by FynnBe** [comment]
I don't see a problem with source pointing to a callable object  as it is language specific, so it may be a class for python
and yes, let's keep it flat...
```yaml
model: 
  source: ./saved_model.pb
  sha256: asdfasdfasdfasdfasdfasdf

weights:  # optional for certain types of model sources
  source: https://zenodo.org/record/... some_weights
  sha256: asdfasdfasdfasdfasdfasdf
```

**Comment by constantinpape** [comment]
Went through the discussion and agree with most of the points.
Two comments from my side:
- I don't think we should restrict to `sha256`, because the hosting service might not offer it. We can still recommend it though.
- How about allowing for an optional `weight` field in `prediction`, because there might be different weights for training and prediction.

**Comment by FynnBe** [comment]
> * I don't think we should restrict to `sha256`, because the hosting service might not offer it. We can still recommend it though.

👍 open question then: stay with the `hash` dict or add a few explicit hash keys like `sha256` ?

> * How about allowing for an optional `weight` field in `prediction`, because there might be different weights for training and prediction.

As training is the more complex part anyhow, how about we add that optional weight field to training? Thinking of meta learning here, that would make more sense to me.

**Comment by constantinpape** [comment]
> +1 open question then: stay with the `hash` dict or add a few explicit hash keys like `sha256` ?

I don't mind either way.

> As training is the more complex part anyhow, how about we add that optional weight field to training? Thinking of meta learning here, that would make more sense to me.

I agree, makes more sense this way.

**Comment by oeway** [comment]
> * I don't think we should restrict to `sha256`, because the hosting service might not offer it. We can still recommend it though.

What do you mean by hosting service? I think the hash value is not generated by the hosting service, it will be generated by the model producer, which is typically a python script, and the hosting service, e.g. Github, Zenodo, etc., they don't need to check integrity, only the consumer software do integrity check. It will be strongly recommended for the consumer for check integrity, but sure, we can make it optional.
> open question then: stay with the hash dict or add a few explicit hash keys like sha256 ?
I think providing multiple types of hashing methods is different from making it optional or not. 
 Since we want to simplify the integrity check implementation, i.e. only one hashing algorithm, I would prefer to use only `sha256` as a key.

> How about allowing for an optional weight field in prediction, because there might be different weights for training and prediction.

Sure, we can add that.
I am also thinking that maybe we can allow a list of weights in the `weights` field? So, one can select whatever weights they want to do prediction or start training/finetuning. Something like:

```
weights:
 - ImageNet:
      source: ...
      sha256: ...
      description: Pretrained weights on ImageNet dataset
      dataset_url: http://image-net.org/imagenet_data/urls/imagenet_fall11_urls.tgz
 - CREMI-padded:
      source: ...
      sha256: ...
      description: Model trained on CRIMI dataset A+ padded version
      dataset_url: https://cremi.org/static/data/sample_A%2B_padded_20160601.hdf
 - CREMI-cropped:
      source: ...
      sha256: ...
      description: Model trained on CRIMI dataset A+ cropped version
      dataset_url: https://cremi.org/static/data/sample_A%2B_20160601.hdf
``` 

In the training or prediction section, we can then use the weights key to refer to which is the default weight for prediction or training. A consumer software can also render the weights list as a UI dropdown menu, let the user to select which weight to use.

**Comment by constantinpape** [comment]
> What do you mean by hosting service? I think the hash value is not generated by the hosting service, it will be generated by the model producer, which is typically a python script, and the hosting service, e.g. Github, Zenodo, etc., they don't need to check integrity, only the consumer software do integrity check. I think it is important the the hash is provided by the producer software (since when the producer upload to hosting service, it may corrupt the file).
> 
> It will be strongly recommended for the consumer for check integrity, but sure, we can make it optional.

Many hosting services generate hashes for you, e.g. zenodo.
But we can also require the producer to provide the hash value and then we can indeed demand it to be `sha256`.

**Comment by oeway** [comment]
A quick note here, in npm package-lock.json file, they use the key `integrity` and `sha512` as hashing algorithm, for example:
```
"integrity": "sha512-cDjOZk8tvxkiRvbZ8Y0SP56FRMRBHj8zlWhyY4IdsE1IRuknSUaQ7vZtlVNlwNveeBeb6LyAZBk4ynl/lyOkOA==",
```
I think we can do the same here.

**Comment by oeway** [comment]
Any final thought here, I would like to summarise this thread and make a PR into the configuration.

We agreed that likely this format would work:
```
model: 
  source: ./saved_model.pb
  sha256: asdfasdfasdfasdfasdfasdf

weights:  # optional for certain types of model sources
  source: https://zenodo.org/record/... some_weights
  sha256: asdfasdfasdfasdfasdfasdf
```
However, considering that we might use different weights for training and testing, and would be nice to support many weights anyway. So I would like propose to wrap the weights with a key:

```yaml
weights:
 - ImageNet:
      source: ...
      sha256: ...
      description: Pretrained weights on ImageNet dataset
      dataset_url: http://image-net.org/imagenet_data/urls/imagenet_fall11_urls.tgz
 - CREMI-padded:
      source: ...
      sha256: ...
      description: Model trained on CRIMI dataset A+ padded version
      dataset_url: https://cremi.org/static/data/sample_A%2B_padded_20160601.hdf
```

Then we can refer to the weight keys inside prediction or training, we can also set a default weights key for the model.

```yaml
prediction:
  weights:  CREMI-padded
  ...
training:
  ...
  setup:
     weights: ImageNet # load pretrained weights
     ...
```

Any final thoughts?
@FynnBe @constantinpape @esgomezm @frauzufall
