### ISSUE TITLE
Compatibility of different fields

### ISSUE THREAD

**Issue by esgomezm** [bioimage-io/configuration#23]
Hi!

We are trying to adapt DeepImageJ to be compatible with the config.yaml, but there are some fields needed that are not present in the YAML. Is it possible to keep them without creating any error when loading them to bioimage.io?

The fields are used to describe two different aspects:

1. TensorFlow model tags (model keys):
```
model_keys:
  # In principle the tag "SERVING" is used in almost every tf model
  model_tag: tf.saved_model.tag_constants.SERVING
  # Signature definition to call the model. Again "SERVING" is the most general
  signature_definition: tf.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY
```
 2. Information about the data provided within the model (example images). 
```
test_information:  
  input_size: [2048x2048] # Size of the input images  
  output_size: [1264x1264 ]# Size of all the outputs  
  device: cpu # Device used. In principle either cpu or GPU  
  memory_peak: 257.7 Mb # Maximum memory consumed by the model in the device  
  runtime: 78.8s # Time it took to run the model
  pixel_size: [9.658E-4µmx9.658E-4µm] # Size of the pixels of the input
```
Also, are you considering adding any similar field?
Thanks!
